azs:
- name: z1




vm_types:
- name: default
  cloud_properties:
    cpus: 2
    memory: 2_096
    ephemeral_disk: 4_096
    paravirtprovider: minimal
- name: large
  cloud_properties:
    cpus: 2
    memory: 2_096
    ephemeral_disk: 10_240
    paravirtprovider: minimal

networks:
- name: private
  type: manual
  subnets:
  - range: 192.168.100.0/24
    gateway: 192.168.100.1
    az: z1
    static:
      192.168.100.11 #used for web config
    cloud_properties:
      name: vboxnet0

disk_types:
- name: default
  disk_size: 1_024

compilation:
  workers: 2
  az: z1
  reuse_compilation_vms: true
  vm_type: large
  network: private
