name: bamboo
director_uuid: e52c94f2-ec50-487b-b97c-0ae55fee1efc

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

releases:
  - name: bamboo
    version: latest
  - name: postgres
    version: latest

update:
  canaries: 1
  max_in_flight: 1 #Should be a small portion of overall capacity to minmize disruption
  canary_watch_time: 1000-600000 # give up to 10 minutes for any running jobs
  update_watch_time: 1000-600000 # give up to 10 minutes for any running jobs
  serial: false


instance_groups:
- name: bamboo-server
  instances: 1
  vm_type: default
  persistent_disk_type: default
  stemcell: trusty
  azs: [z1]
  networks:
  - name: private
    static_ips: [192.168.100.11] #from cloud config reserved IP
  jobs:
  - name: bamboo
    release: bamboo
    consumes:
      data-db: {from: postgres-database}
    provides:
      bamboo-server: {as: bamboo-master}
    properties:
      server:
        port: 1999
- name: agents
  instances: 2
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: default
  persistent_disk_type: default
  stemcell: trusty
  azs: [z1]
  networks:
  - name: private
  jobs:
  - name: bamboo-agent
    release: bamboo
    properties:
      api:
        enabled: true #only enable APIs if using persistent disk
        token:
          uuid: cd94f47f-7659-416c-ac35-c552f4e66f7f  #replaced with an read/write API token for Bamboo-Agent-APIs
    consumes:
      bamboo-server: {from: bamboo-master}
- name: postgres
  instances: 1
  stemcell: trusty
  persistent_disk_type: default
  vm_type: default
  azs: [z1]
  networks:
  - name: private
  jobs:
  - name: postgres
    release: postgres
    properties:
      databases:
        port: 5432
        databases:
          - name: bamboo
        roles:
          - name: bamboo
            password: password  # for postgres suggested deploy is using certs https://github.com/cloudfoundry/postgres-release#enabling-ssl-on-the-postgresql-server
    provides:
      postgres:
        as: postgres-database
