name: bamboo
director_uuid: e52c94f2-ec50-487b-b97c-0ae55fee1efc

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

releases:
  - name: bamboo
    version: latest

update:
  canaries: 1
  max_in_flight: 1 #Should be a small portion of overall capacity to minmize disruption
  canary_watch_time: 1000-600000 # give up to 10 minutes for any running jobs
  update_watch_time: 1000-600000 # give up to 10 minutes for any running jobs
  serial: false


instance_groups:
- name: agents
  instances: 2
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: default
  persistent_disk_type: default
  stemcell: trusty
  azs: [z1]
  networks:
  - name: private
  jobs:
  - name: bamboo-agent
    release: bamboo
    properties:
      server:
        ip: 192.168.50.1 # use the gateway IP configured in virtual box networks.
        port: 6990
        protocol: http
        context: /bamboo/
      api:
        enabled: true #only enable APIs if using persistent disk
        token:
          uuid: cd94f47f-7659-416c-ac35-c552f4e66f7f  #replaced with an read/write API token for Bamboo-Agent-APIs
